package com.littlehelper.fabiaoqing.domainobject;

import java.io.Serializable;
import java.util.Date;

public class PackageDO extends PackageDOKey implements Serializable {
    private static final long serialVersionUID = 7702355712187255628L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_package.name
     *
     * @mbg.generated Thu May 30 09:54:43 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_package.seq
     *
     * @mbg.generated Thu May 30 09:54:43 CST 2019
     */
    private Integer seq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_package.create_time
     *
     * @mbg.generated Thu May 30 09:54:43 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_package.update_time
     *
     * @mbg.generated Thu May 30 09:54:43 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_package.name
     *
     * @return the value of t_package.name
     *
     * @mbg.generated Thu May 30 09:54:43 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_package.name
     *
     * @param name the value for t_package.name
     *
     * @mbg.generated Thu May 30 09:54:43 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_package.seq
     *
     * @return the value of t_package.seq
     *
     * @mbg.generated Thu May 30 09:54:43 CST 2019
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_package.seq
     *
     * @param seq the value for t_package.seq
     *
     * @mbg.generated Thu May 30 09:54:43 CST 2019
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_package.create_time
     *
     * @return the value of t_package.create_time
     *
     * @mbg.generated Thu May 30 09:54:43 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_package.create_time
     *
     * @param createTime the value for t_package.create_time
     *
     * @mbg.generated Thu May 30 09:54:43 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_package.update_time
     *
     * @return the value of t_package.update_time
     *
     * @mbg.generated Thu May 30 09:54:43 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_package.update_time
     *
     * @param updateTime the value for t_package.update_time
     *
     * @mbg.generated Thu May 30 09:54:43 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}