package com.littlehelper.fabiaoqing.dao;

import com.littlehelper.fabiaoqing.domainobject.CategoryDO;

import java.util.List;

public interface CategoryDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbg.generated Wed May 29 16:18:58 CST 2019
     */
    int deleteByPrimaryKey(String objectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbg.generated Wed May 29 16:18:58 CST 2019
     */
    int insert(CategoryDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbg.generated Wed May 29 16:18:58 CST 2019
     */
    int insertSelective(CategoryDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbg.generated Wed May 29 16:18:58 CST 2019
     */
    CategoryDO selectByPrimaryKey(String objectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbg.generated Wed May 29 16:18:58 CST 2019
     */
    int updateByPrimaryKeySelective(CategoryDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbg.generated Wed May 29 16:18:58 CST 2019
     */
    int updateByPrimaryKey(CategoryDO record);

    List<CategoryDO> selectAll();
}