package com.littlehelper.fabiaoqing.dao;

import com.littlehelper.fabiaoqing.domainobject.EmoticonDO;
import com.littlehelper.fabiaoqing.domainobject.EmoticonDOKey;

import java.util.List;

public interface EmoticonDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emoticon
     *
     * @mbg.generated Thu May 30 11:31:34 CST 2019
     */
    int deleteByPrimaryKey(EmoticonDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emoticon
     *
     * @mbg.generated Thu May 30 11:31:34 CST 2019
     */
    int insert(EmoticonDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emoticon
     *
     * @mbg.generated Thu May 30 11:31:34 CST 2019
     */
    int insertSelective(EmoticonDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emoticon
     *
     * @mbg.generated Thu May 30 11:31:34 CST 2019
     */
    EmoticonDO selectByPrimaryKey(EmoticonDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emoticon
     *
     * @mbg.generated Thu May 30 11:31:34 CST 2019
     */
    int updateByPrimaryKeySelective(EmoticonDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emoticon
     *
     * @mbg.generated Thu May 30 11:31:34 CST 2019
     */
    int updateByPrimaryKey(EmoticonDO record);

    Integer countByParentId(String parentId);

    List<EmoticonDO> selectByObjectId(String objectId);

    List<EmoticonDO> selectByParentId(String parentId);
}